/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Education {
  'field' : string,
  'startYear' : bigint,
  'endYear' : [] | [bigint],
  'institution' : string,
  'degree' : string,
}
export interface Hobby {
  'icon' : string,
  'name' : string,
  'description' : string,
}
export interface Portfolio {
  'education' : Array<Education>,
  'workExperience' : Array<WorkExperience>,
  'skills' : Array<Skill>,
  'profile' : Profile,
  'hobbies' : Array<Hobby>,
}
export interface Profile {
  'bio' : string,
  'linkedIn' : string,
  'title' : string,
  'name' : string,
  'email' : string,
  'avatarUrl' : string,
  'location' : string,
  'github' : string,
}
export interface Skill {
  'achieved' : boolean,
  'achievedDate' : [] | [bigint],
  'name' : string,
  'progress' : bigint,
  'category' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkExperience {
  'endDate' : [] | [bigint],
  'role' : string,
  'description' : string,
  'company' : string,
  'startDate' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEducation' : ActorMethod<[Education], bigint>,
  'addHobby' : ActorMethod<[Hobby], bigint>,
  'addSkill' : ActorMethod<[Skill], bigint>,
  'addWorkExperience' : ActorMethod<[WorkExperience], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFullPortfolio' : ActorMethod<[], Portfolio>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markSkillAchieved' : ActorMethod<[bigint], undefined>,
  'removeEducation' : ActorMethod<[bigint], undefined>,
  'removeHobby' : ActorMethod<[bigint], undefined>,
  'removeSkill' : ActorMethod<[bigint], undefined>,
  'removeWorkExperience' : ActorMethod<[bigint], undefined>,
  'updateEducation' : ActorMethod<[bigint, Education], undefined>,
  'updateHobby' : ActorMethod<[bigint, Hobby], undefined>,
  'updateProfile' : ActorMethod<[Profile], undefined>,
  'updateSkill' : ActorMethod<[bigint, Skill], undefined>,
  'updateSkillProgress' : ActorMethod<[bigint, bigint], undefined>,
  'updateWorkExperience' : ActorMethod<[bigint, WorkExperience], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];