/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Education = IDL.Record({
  'field' : IDL.Text,
  'startYear' : IDL.Nat64,
  'endYear' : IDL.Opt(IDL.Nat64),
  'institution' : IDL.Text,
  'degree' : IDL.Text,
});
export const Hobby = IDL.Record({
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Skill = IDL.Record({
  'achieved' : IDL.Bool,
  'achievedDate' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'progress' : IDL.Nat,
  'category' : IDL.Text,
});
export const WorkExperience = IDL.Record({
  'endDate' : IDL.Opt(IDL.Nat64),
  'role' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'startDate' : IDL.Nat64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'linkedIn' : IDL.Text,
  'title' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'location' : IDL.Text,
  'github' : IDL.Text,
});
export const Portfolio = IDL.Record({
  'education' : IDL.Vec(Education),
  'workExperience' : IDL.Vec(WorkExperience),
  'skills' : IDL.Vec(Skill),
  'profile' : Profile,
  'hobbies' : IDL.Vec(Hobby),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEducation' : IDL.Func([Education], [IDL.Nat], []),
  'addHobby' : IDL.Func([Hobby], [IDL.Nat], []),
  'addSkill' : IDL.Func([Skill], [IDL.Nat], []),
  'addWorkExperience' : IDL.Func([WorkExperience], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFullPortfolio' : IDL.Func([], [Portfolio], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markSkillAchieved' : IDL.Func([IDL.Nat], [], []),
  'removeEducation' : IDL.Func([IDL.Nat], [], []),
  'removeHobby' : IDL.Func([IDL.Nat], [], []),
  'removeSkill' : IDL.Func([IDL.Nat], [], []),
  'removeWorkExperience' : IDL.Func([IDL.Nat], [], []),
  'updateEducation' : IDL.Func([IDL.Nat, Education], [], []),
  'updateHobby' : IDL.Func([IDL.Nat, Hobby], [], []),
  'updateProfile' : IDL.Func([Profile], [], []),
  'updateSkill' : IDL.Func([IDL.Nat, Skill], [], []),
  'updateSkillProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateWorkExperience' : IDL.Func([IDL.Nat, WorkExperience], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Education = IDL.Record({
    'field' : IDL.Text,
    'startYear' : IDL.Nat64,
    'endYear' : IDL.Opt(IDL.Nat64),
    'institution' : IDL.Text,
    'degree' : IDL.Text,
  });
  const Hobby = IDL.Record({
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Skill = IDL.Record({
    'achieved' : IDL.Bool,
    'achievedDate' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'progress' : IDL.Nat,
    'category' : IDL.Text,
  });
  const WorkExperience = IDL.Record({
    'endDate' : IDL.Opt(IDL.Nat64),
    'role' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'startDate' : IDL.Nat64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'linkedIn' : IDL.Text,
    'title' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'location' : IDL.Text,
    'github' : IDL.Text,
  });
  const Portfolio = IDL.Record({
    'education' : IDL.Vec(Education),
    'workExperience' : IDL.Vec(WorkExperience),
    'skills' : IDL.Vec(Skill),
    'profile' : Profile,
    'hobbies' : IDL.Vec(Hobby),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEducation' : IDL.Func([Education], [IDL.Nat], []),
    'addHobby' : IDL.Func([Hobby], [IDL.Nat], []),
    'addSkill' : IDL.Func([Skill], [IDL.Nat], []),
    'addWorkExperience' : IDL.Func([WorkExperience], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFullPortfolio' : IDL.Func([], [Portfolio], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markSkillAchieved' : IDL.Func([IDL.Nat], [], []),
    'removeEducation' : IDL.Func([IDL.Nat], [], []),
    'removeHobby' : IDL.Func([IDL.Nat], [], []),
    'removeSkill' : IDL.Func([IDL.Nat], [], []),
    'removeWorkExperience' : IDL.Func([IDL.Nat], [], []),
    'updateEducation' : IDL.Func([IDL.Nat, Education], [], []),
    'updateHobby' : IDL.Func([IDL.Nat, Hobby], [], []),
    'updateProfile' : IDL.Func([Profile], [], []),
    'updateSkill' : IDL.Func([IDL.Nat, Skill], [], []),
    'updateSkillProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateWorkExperience' : IDL.Func([IDL.Nat, WorkExperience], [], []),
  });
};

export const init = ({ IDL }) => { return []; };