/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Skill {
    achieved: boolean;
    achievedDate?: bigint;
    name: string;
    progress: bigint;
    category: string;
}
export interface WorkExperience {
    endDate?: bigint;
    role: string;
    description: string;
    company: string;
    startDate: bigint;
}
export interface Education {
    field: string;
    startYear: bigint;
    endYear?: bigint;
    institution: string;
    degree: string;
}
export interface Portfolio {
    education: Array<Education>;
    workExperience: Array<WorkExperience>;
    skills: Array<Skill>;
    profile: Profile;
    hobbies: Array<Hobby>;
}
export interface Hobby {
    icon: string;
    name: string;
    description: string;
}
export interface Profile {
    bio: string;
    linkedIn: string;
    title: string;
    name: string;
    email: string;
    avatarUrl: string;
    location: string;
    github: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addEducation(entry: Education): Promise<bigint>;
    addHobby(hobby: Hobby): Promise<bigint>;
    addSkill(skill: Skill): Promise<bigint>;
    addWorkExperience(entry: WorkExperience): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getFullPortfolio(): Promise<Portfolio>;
    isCallerAdmin(): Promise<boolean>;
    markSkillAchieved(id: bigint): Promise<void>;
    removeEducation(id: bigint): Promise<void>;
    removeHobby(id: bigint): Promise<void>;
    removeSkill(id: bigint): Promise<void>;
    removeWorkExperience(id: bigint): Promise<void>;
    updateEducation(id: bigint, entry: Education): Promise<void>;
    updateHobby(id: bigint, hobby: Hobby): Promise<void>;
    updateProfile(profile: Profile): Promise<void>;
    updateSkill(id: bigint, skill: Skill): Promise<void>;
    updateSkillProgress(id: bigint, progress: bigint): Promise<void>;
    updateWorkExperience(id: bigint, entry: WorkExperience): Promise<void>;
}
import type { Education as _Education, Hobby as _Hobby, Portfolio as _Portfolio, Profile as _Profile, Skill as _Skill, UserRole as _UserRole, WorkExperience as _WorkExperience } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addEducation(arg0: Education): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addEducation(to_candid_Education_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEducation(to_candid_Education_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addHobby(arg0: Hobby): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addHobby(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHobby(arg0);
            return result;
        }
    }
    async addSkill(arg0: Skill): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSkill(to_candid_Skill_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSkill(to_candid_Skill_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addWorkExperience(arg0: WorkExperience): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkExperience(to_candid_WorkExperience_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkExperience(to_candid_WorkExperience_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFullPortfolio(): Promise<Portfolio> {
        if (this.processError) {
            try {
                const result = await this.actor.getFullPortfolio();
                return from_candid_Portfolio_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFullPortfolio();
            return from_candid_Portfolio_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markSkillAchieved(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markSkillAchieved(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markSkillAchieved(arg0);
            return result;
        }
    }
    async removeEducation(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeEducation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeEducation(arg0);
            return result;
        }
    }
    async removeHobby(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeHobby(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeHobby(arg0);
            return result;
        }
    }
    async removeSkill(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSkill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSkill(arg0);
            return result;
        }
    }
    async removeWorkExperience(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeWorkExperience(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeWorkExperience(arg0);
            return result;
        }
    }
    async updateEducation(arg0: bigint, arg1: Education): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEducation(arg0, to_candid_Education_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEducation(arg0, to_candid_Education_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateHobby(arg0: bigint, arg1: Hobby): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHobby(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHobby(arg0, arg1);
            return result;
        }
    }
    async updateProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0);
            return result;
        }
    }
    async updateSkill(arg0: bigint, arg1: Skill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSkill(arg0, to_candid_Skill_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSkill(arg0, to_candid_Skill_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSkillProgress(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSkillProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSkillProgress(arg0, arg1);
            return result;
        }
    }
    async updateWorkExperience(arg0: bigint, arg1: WorkExperience): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkExperience(arg0, to_candid_WorkExperience_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkExperience(arg0, to_candid_WorkExperience_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Education_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Education): Education {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Portfolio_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Portfolio): Portfolio {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Skill_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Skill): Skill {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_WorkExperience_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkExperience): WorkExperience {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    education: Array<_Education>;
    workExperience: Array<_WorkExperience>;
    skills: Array<_Skill>;
    profile: _Profile;
    hobbies: Array<_Hobby>;
}): {
    education: Array<Education>;
    workExperience: Array<WorkExperience>;
    skills: Array<Skill>;
    profile: Profile;
    hobbies: Array<Hobby>;
} {
    return {
        education: from_candid_vec_n13(_uploadFile, _downloadFile, value.education),
        workExperience: from_candid_vec_n17(_uploadFile, _downloadFile, value.workExperience),
        skills: from_candid_vec_n20(_uploadFile, _downloadFile, value.skills),
        profile: value.profile,
        hobbies: value.hobbies
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    field: string;
    startYear: bigint;
    endYear: [] | [bigint];
    institution: string;
    degree: string;
}): {
    field: string;
    startYear: bigint;
    endYear?: bigint;
    institution: string;
    degree: string;
} {
    return {
        field: value.field,
        startYear: value.startYear,
        endYear: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.endYear)),
        institution: value.institution,
        degree: value.degree
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate: [] | [bigint];
    role: string;
    description: string;
    company: string;
    startDate: bigint;
}): {
    endDate?: bigint;
    role: string;
    description: string;
    company: string;
    startDate: bigint;
} {
    return {
        endDate: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.endDate)),
        role: value.role,
        description: value.description,
        company: value.company,
        startDate: value.startDate
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    achieved: boolean;
    achievedDate: [] | [bigint];
    name: string;
    progress: bigint;
    category: string;
}): {
    achieved: boolean;
    achievedDate?: bigint;
    name: string;
    progress: bigint;
    category: string;
} {
    return {
        achieved: value.achieved,
        achievedDate: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.achievedDate)),
        name: value.name,
        progress: value.progress,
        category: value.category
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Education>): Array<Education> {
    return value.map((x)=>from_candid_Education_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkExperience>): Array<WorkExperience> {
    return value.map((x)=>from_candid_WorkExperience_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Skill>): Array<Skill> {
    return value.map((x)=>from_candid_Skill_n21(_uploadFile, _downloadFile, x));
}
function to_candid_Education_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Education): _Education {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Skill_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Skill): _Skill {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_WorkExperience_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkExperience): _WorkExperience {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    field: string;
    startYear: bigint;
    endYear?: bigint;
    institution: string;
    degree: string;
}): {
    field: string;
    startYear: bigint;
    endYear: [] | [bigint];
    institution: string;
    degree: string;
} {
    return {
        field: value.field,
        startYear: value.startYear,
        endYear: value.endYear ? candid_some(value.endYear) : candid_none(),
        institution: value.institution,
        degree: value.degree
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    achieved: boolean;
    achievedDate?: bigint;
    name: string;
    progress: bigint;
    category: string;
}): {
    achieved: boolean;
    achievedDate: [] | [bigint];
    name: string;
    progress: bigint;
    category: string;
} {
    return {
        achieved: value.achieved,
        achievedDate: value.achievedDate ? candid_some(value.achievedDate) : candid_none(),
        name: value.name,
        progress: value.progress,
        category: value.category
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate?: bigint;
    role: string;
    description: string;
    company: string;
    startDate: bigint;
}): {
    endDate: [] | [bigint];
    role: string;
    description: string;
    company: string;
    startDate: bigint;
} {
    return {
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        role: value.role,
        description: value.description,
        company: value.company,
        startDate: value.startDate
    };
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
